/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color System
        "secondary-container": "#82f5c1",
        "outline-variant": "#c3c5d7",
        "outline": "#737686",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-highest": "#dce2f3",
        "primary-container": "#1a56db",
        "on-background": "#151c27",
        "tertiary-fixed": "#ffdcc3",
        "surface-dim": "#d3daea",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00174d",
        "surface-variant": "#dce2f3",
        "tertiary": "#723b00",
        "error-container": "#ffdad6",
        "background": "#f9f9ff",
        "on-primary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9ff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#005137",
        "surface-container-high": "#e2e8f8",
        "surface-tint": "#1353d8",
        "on-secondary-container": "#00714e",
        "on-error": "#ffffff",
        "inverse-surface": "#2a313d",
        "primary": "#003fb1",
        "secondary-fixed-dim": "#68dba9",
        "on-tertiary-container": "#ffd5b6",
        "on-surface": "#151c27",
        "surface-bright": "#f9f9ff",
        "on-primary-fixed-variant": "#003dab",
        "on-error-container": "#93000a",
        "secondary-fixed": "#85f8c4",
        "on-secondary-fixed": "#002114",
        "secondary": "#006c4a",
        "inverse-on-surface": "#ebf1ff",
        "surface-container": "#e7eefe",
        "tertiary-fixed-dim": "#ffb77d",
        "tertiary-container": "#954f00",
        "primary-fixed-dim": "#b5c4ff",
        "on-primary-container": "#d4dcff",
        "on-surface-variant": "#434654",
        "inverse-primary": "#b5c4ff",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-fixed": "#2f1500",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
      },
      fontSize: {
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-lg": [
          "28px",
          {
            lineHeight: "36px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
